//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_LAP.ExtraCharge {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExtraCharge.IExtraCharge")]
    public interface IExtraCharge {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtraCharge/ExtraChargeValue", ReplyAction="http://tempuri.org/IExtraCharge/ExtraChargeValueResponse")]
        double ExtraChargeValue(double CostPrice, double percent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtraCharge/ExtraChargeValue", ReplyAction="http://tempuri.org/IExtraCharge/ExtraChargeValueResponse")]
        System.Threading.Tasks.Task<double> ExtraChargeValueAsync(double CostPrice, double percent);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExtraChargeChannel : WEB_LAP.ExtraCharge.IExtraCharge, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExtraChargeClient : System.ServiceModel.ClientBase<WEB_LAP.ExtraCharge.IExtraCharge>, WEB_LAP.ExtraCharge.IExtraCharge {
        
        public ExtraChargeClient() {
        }
        
        public ExtraChargeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExtraChargeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExtraChargeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExtraChargeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double ExtraChargeValue(double CostPrice, double percent) {
            return base.Channel.ExtraChargeValue(CostPrice, percent);
        }
        
        public System.Threading.Tasks.Task<double> ExtraChargeValueAsync(double CostPrice, double percent) {
            return base.Channel.ExtraChargeValueAsync(CostPrice, percent);
        }
    }
}
